export ZSH=${HOME}/.oh-my-zsh

ZSH_THEME="blox"

HIST_STAMPS="yyyy-mm-dd"

ZSH_CUSTOM=${HOME}/.oh-my-zsh-custom

plugins=(git notify-completion zsh-autosuggestions)

OH_MY_ZSH_BOOTSTRAP=${ZSH}/oh-my-zsh.sh
if [ -f "$OH_MY_ZSH_BOOTSTRAP" ]
then
    source $ZSH/oh-my-zsh.sh
fi

# Language
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='code'
fi

# Aliases
alias please='sudo $(fc -ln -1)'
alias ll='ls -lAh'
alias vi=vim

# man page option completion
zstyle ':completion:*:manuals'    separate-sections true
zstyle ':completion:*:manuals.*'  insert-sections   true
zstyle ':completion:*:man:*'      menu yes select

# thefuck
eval $(thefuck --alias)

# n (node version manager)
export N_PREFIX="$HOME/Applications/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).

# SDKMAN (must be at end of file)
export SDKMAN_DIR="/home/gustav/.sdkman"
[[ -s "/home/gustav/.sdkman/bin/sdkman-init.sh" ]] && source "/home/gustav/.sdkman/bin/sdkman-init.sh"
