export ZSH=${HOME}/.oh-my-zsh

ZSH_THEME="spaceship"

HIST_STAMPS="yyyy-mm-dd"

ZSH_CUSTOM=${HOME}/.oh-my-zsh-custom

plugins=(git notify-completion zsh-autosuggestions k)

OH_MY_ZSH_BOOTSTRAP=${ZSH}/oh-my-zsh.sh
if [ -f "$OH_MY_ZSH_BOOTSTRAP" ]
then
    source $ZSH/oh-my-zsh.sh
fi

# Spaceshipt prompt
SPACESHIP_PROMPT_ORDER=(
  time          # Time stamps section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  package       # Package version
  node          # Node.js section
  golang        # Go section
  docker        # Docker section
  venv          # virtualenv section
  conda         # conda virtualenv section
  pyenv         # Pyenv section
  exec_time     # Execution time
  line_sep      # Line break
  battery       # Battery level and status
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)
SPACESHIP_EXIT_CODE_SHOW=true

# Language
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='code'
fi

# Aliases
alias please='sudo $(fc -ln -1)'
alias ll='ls -lAh'
alias vim=vi

# man page option completion
zstyle ':completion:*:manuals'    separate-sections true
zstyle ':completion:*:manuals.*'  insert-sections   true
zstyle ':completion:*:man:*'      menu yes select

# thefuck
eval $(thefuck --alias)

# n (node version manager)
export N_PREFIX="$HOME/Applications/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).

# SDKMAN (must be at end of file)
export SDKMAN_DIR="/home/gustav/.sdkman"
[[ -s "/home/gustav/.sdkman/bin/sdkman-init.sh" ]] && source "/home/gustav/.sdkman/bin/sdkman-init.sh"
